### ISSUE TITLE
Constant sunrise in dimension which type has undefined fixed_time

### ISSUE THREAD

**Issue by ScarletBlizzard** [TBMCPlugins/CustomDimensions#2]
Contents of dimension_type/custom_type.json in my datapack:
```
{
  "ultrawarm": false,
  "natural": true,
  "piglin_safe": false,
  "respawn_anchor_works": true,
  "bed_works": false,
  "has_raids": false,
  "has_skylight": true,
  "has_ceiling": false,
  "coordinate_scale": 1,
  "ambient_light": 0,
  "logical_height": 256,
  "infiniburn": "minecraft:infiniburn_overworld"
}
```
As expected, there is a normal day/night cycle in my custom dimension with type "minecraft:custom_type" in singleplayer world with my datapack installed.
However, on server which has only CustomDimensions plugin and the same datapack installed, the same dimension has endless sunrise and the sun is twitching back and forth a little bit. But there should be a normal day/night cycle because fixed_time is not defined.

Server: Paper 1.16.3 #192

**Comment by NorbiPeti** [comment]
Thanks for the report, I overlooked this. The vanilla server disables the handling of time for custom dimensions, I guess as it's handled by the main world. It should be fixed in [1.2](https://www.spigotmc.org/resources/1-16-custom-dimensions.83731/update?update=361047), please let me know if you still have the issue.
